language: go 

env: GO111MODULE=on

jobs:
  include:
    - go: 1.12.x  
      script: go test -v -race ./...
      os: linux 
    - go: 1.11.x  
      script: go test -v -race ./...
      os: linux 
    - go: 1.12.x  
      script: go test -v -race ./...
      os: osx
    - go: 1.11.x  
      script: go test -v -race ./...
      os: osx 
    - go: 1.12.x  
      script: go test -v -race ./...
      os: windows 
